### ISSUE TITLE
What is a rbr rebase?

### ISSUE THREAD

**Issue by bbigras** [fanatoly/magit-rbr#2]
magit-rbr nor git-rbr repo say what an rbr rebase is but I'm interested to know what it is.

**Comment by fanatoly** [comment]
rbr recursively rebases any branches that indicate the current branch as their upstream. For example, when you have 
```
A+->B
+
+->C(branch C)+->D(branch D)
   +
   +->E(branch E)
```
rebasing branch C onto change B with rbr will yield
```
A+->B
    +
    +->C(branch C)+->D(branch D)
       +
       +->E(branch E)
```

I agree that git rbr probably needs better docs. I am certain that they will appreciate pull requests!

**Comment by bbigras** [comment]
Thank you very much.
